#!/usr/bin/env bash
# The whole board top, simulated. Validates the INSTRUMENT, not the crossing.
#
#   bash cdc-demo/sim/run_top.sh [a|b|c|e|f|g]
#
# Verilog samples old-or-new and models no metastability, so arm B is clean here
# however broken the crossing is. What this checks is everything around it: that
# the reset tree releases, that both sinks see items in order, and that the
# report line is well formed with the counters in the right positions. A garbled
# report on the board would look exactly like a broken DUT.
#
# The report dividers are shrunk through CHAR_DIV_BITS and RPT_TICK_BITS so a
# line takes microseconds instead of a second. Only the widths differ.
set -u
QUESTA="${QUESTA:-/e/Quartus/questa_fse/win64}"
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
DDL="${DDL:-$ROOT/target/release/ddl.exe}"
ARM="${1:-b}"
W="$HERE/work_top"

case "$ARM" in
    a) DEF='`define ARM_A';   CH="8'h41"; S1=0; DV=0; S2="" ;;
    b) DEF='`define ARM_B';   CH="8'h42"; S1=0; DV=0; S2="" ;;
    c) DEF='`define ARM_C';   CH="8'h43"; S1=1; DV=0; S2='`define SLOT2_SYNC' ;;
    e) DEF='`define ARM_E';   CH="8'h45"; S1=0; DV=0; S2="" ;;
    f) DEF='`define ARM_F';   CH="8'h46"; S1=0; DV=1; S2="" ;;
    g) DEF='`define ARM_G';   CH="8'h47"; S1=0; DV=0; S2="" ;;
    *) echo "usage: run_top.sh [a|b|c|e|f|g]" >&2; exit 1 ;;
esac

rm -rf "$W"; mkdir -p "$W"
{
    echo "// GENERATED by run_top.sh -- arm $ARM, pair 0, simulation dividers."
    echo "$DEF"
    [ -n "$S2" ] && echo "$S2"
    echo "\`define ARM_CHAR $CH"
    echo "\`define SLOT1_SYNC $S1"
    echo "\`define SLOT1_DERIVE $DV"
    echo '`define PLL_A_IDIV  0'
    echo '`define PLL_A_FBDIV 2'
    echo '`define PLL_A_ODIV  8'
    echo '`define PLL_B_IDIV  0'
    echo '`define PLL_B_FBDIV 3'
    echo '`define PLL_B_ODIV  8'
    echo '`define UART_DIVISOR 8'
    echo '`define RPT_TICK_BITS 18'
    echo '`define CHAR_DIV_BITS 8'
    echo '`define SIM_A_HZ 81000000'
    echo '`define SIM_B_HZ 108000000'
} > "$W/arm_config.vh"

sed -e "s/@NAME@/cdc_pll_a/" -e "s/@IDIV@/0/" -e "s/@FBDIV@/2/" -e "s/@ODIV@/8/" \
    "$HERE/../cdc_pll.v.in" > "$W/cdc_pll_gen.v"
sed -e "s/@NAME@/cdc_pll_b/" -e "s/@IDIV@/0/" -e "s/@FBDIV@/3/" -e "s/@ODIV@/8/" \
    "$HERE/../cdc_pll.v.in" | sed -n '/^module /,$p' >> "$W/cdc_pll_gen.v"

# Arm G is the same source through --async-export, and the emitted file is used
# exactly as written. This bench cannot show a crossing failing -- Verilog
# samples old-or-new -- but it does show the wiring, the reset handshake
# releasing on both sides, and the throughput each slot settles at, all of which
# are worth knowing before a bitstream is burned.
if [ "$ARM" = "g" ]; then
    "$DDL" build "$HERE/../gen_chk.ddl" --export gen,chk         --async-export gen.o=rx --async-export chk.src=tx         -o "$W/gen_chk_async.v" || exit 1
else
    "$DDL" build "$HERE/../gen_chk.ddl" --bare-export gen,chk -o "$W/gen_chk.v" || exit 1
fi

SRC=("$HERE/rpll_model.sv" "$W/cdc_pll_gen.v" "$HERE/../cdc_uart.v")
if   [ "$ARM" = "e" ]; then SRC+=("$HERE/../cdc_fifo.v")
elif [ "$ARM" = "g" ]; then SRC+=("$W/gen_chk_async.v")
else                        SRC+=("$HERE/../pipe_cdc.v" "$W/gen_chk.v"); fi
SRC+=("$HERE/../cdc_demo_top.v" "$HERE/tb_top.sv")

cd "$W"
"$QUESTA/vlib.exe" work >/dev/null || exit 1
"$QUESTA/vlog.exe" -quiet -sv +incdir+. "${SRC[@]}" || exit 1
"$QUESTA/vsim.exe" -quiet -c -do "run -all; quit -f" tb_top 2>&1 |
    sed 's/^# //' |
    grep -vE '^//|Siemens|trade secrets|limited as set|material may not|of the Customer|and may not be|owned by|^$'
